data = [
  {
    "id": "rx",
    "x": 0,
    "y": 0,
    "imgSmall": "rx01-small.jpg",
    "imgLarge": "rx01-large.jpg",
    "date": "2017-10-25",
    "seq": 1
  },
  {
    "id": "ls",
    "x": 1,
    "y": 0,
    "imgSmall": "ls01-small.jpg",
    "imgLarge": "ls01-large.jpg",
    "date": "2017-10-25",
    "seq": 2
  },
  {
    "id": "tt",
    "x": -1,
    "y": 0,
    "imgSmall": "tt01-small.jpg",
    "imgLarge": "tt01-large.jpg",
    "date": "2017-10-26",
    "seq": 3
  },
  {
    "id": "rx",
    "x": 2,
    "y": 0,
    "imgSmall": "rx02-small.jpg",
    "imgLarge": "rx02-large.jpg",
    "date": "2017-10-26",
    "seq": 4
  },
  {
    "id": "lz",
    "x": 1,
    "y": -1,
    "imgSmall": "lz01-small.jpg",
    "imgLarge": "lz01-large.jpg",
    "date": "2017-10-28",
    "seq": 5,
  },
  {
    "id": "ed",
    "x": -2,
    "y": 0,
    "imgSmall": "ed01-small.jpg",
    "imgLarge": "ed01-large.jpg",
    "date": "2017-10-29",
    "seq": 6,
  },
  {
    "id": "lz",
    "x": -2,
    "y": 1,
    "imgSmall": "lz02-small.jpg",
    "imgLarge": "lz02-large.jpg",
    "date": "2017-10-30",
    "seq": 7,
  },
  {
    "id": "ie",
    "x": 2,
    "y": -1,
    "imgSmall": "ie01-small.jpg",
    "imgLarge": "ie01-large.jpg",
    "date": "2017-10-30",
    "seq": 8,
  },
  {
    "id": "zl",
    "x": 0,
    "y": -1,
    "imgSmall": "zl01-small.jpg",
    "imgLarge": "zl01-large.jpg",
    "date": "2017-10-30",
    "seq": 9,
  },
    {
    "id": "zl",
    "x": -2,
    "y": -1,
    "imgSmall": "zl02-small.jpg",
    "imgLarge": "zl02-large.jpg",
    "date": "2017-10-30",
    "seq": 10,
  },
  {
    "id": "ja",
    "x": 0,
    "y": 1,
    "imgSmall": "ja01-small.jpg",
    "imgLarge": "ja01-large.jpg",
    "date": "2017-10-30",
    "seq": 11,
  },
  {
    "id": "tt",
    "x": 2,
    "y": -2,
    "imgSmall": "tt02-small.jpg",
    "imgLarge": "tt02-large.jpg",
    "date": "2017-10-31",
    "seq": 12,
  },
    {
    "id": "ed",
    "x": 2,
    "y": 1,
    "imgSmall": "ed02-small.jpg",
    "imgLarge": "ed02-large.jpg",
    "date": "2017-10-31",
    "seq": 13,
  },
  {
    "id": "ja",
    "x": 1,
    "y": -2,
    "imgSmall": "ja02-small.jpg",
    "imgLarge": "ja02-large.jpg",
    "date": "2017-11-01",
    "seq": 14,
  },
  {
    "id": "ls",
    "x": 1,
    "y": -3,
    "imgSmall": "ls02-small.jpg",
    "imgLarge": "ls02-large.jpg",
    "date": "2017-11-01",
    "seq": 15,
  },
  {
    "id": "ls",
    "x": -3,
    "y": 0,
    "imgSmall": "ls03-small.jpg",
    "imgLarge": "ls03-large.jpg",
    "date": "2017-11-01",
    "seq": 16,
  }, 
  {
    "id": "cx",
    "x": 0,
    "y": 2,
    "imgSmall": "cx01-small.jpg",
    "imgLarge": "cx01-large.jpg",
    "date": "2017-11-01",
    "seq": 17,
  },
{
    "id": "cx",
    "x": 3,
    "y": 0,
    "imgSmall": "cx02-small.jpg",
    "imgLarge": "cx02-large.jpg",
    "date": "2017-11-01",
    "seq": 18,
  },
 {
    "id": "cx",
    "x": -1,
    "y": 1,
    "imgSmall": "cx03-small.jpg",
    "imgLarge": "cx03-large.jpg",
    "date": "2017-11-01",
    "seq": 19,
  },
  {
    "id": "tt",
    "x": 4,
    "y": 0,
    "imgSmall": "tt03-small.jpg",
    "imgLarge": "tt03-large.jpg",
    "date": "2017-11-02",
    "seq": 20,
  },
  {
    "id": "rx",
    "x": 2,
    "y": 2,
    "imgSmall": "rx03-small.jpg",
    "imgLarge": "rx03-large.jpg",
    "date": "2017-11-04",
    "seq": 21,
  },
  {
    "id": "ls",
    "x": 2,
    "y": -3,
    "imgSmall": "ls04-small.jpg",
    "imgLarge": "ls04-large.jpg",
    "date": "2017-11-04",
    "seq": 22,
  },
  {
    "id": "lz",
    "x": 3,
    "y": 2,
    "imgSmall": "lz03-small.jpg",
    "imgLarge": "lz03-large.jpg",
    "date": "2017-11-05",
    "seq": 23,
  },
  {
    "id": "tt",
    "x": -2,
    "y": 2,
    "imgSmall": "tt04-small.jpg",
    "imgLarge": "tt04-large.jpg",
    "date": "2017-11-05",
    "seq": 24,
  },
 ]; 